/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as ArchiveIndexRouteImport } from './routes/archive.index'
import { Route as ArchiveSlugRouteImport } from './routes/archive.$slug'
import { Route as MaisonTerminalRouteImport } from './routes/maison.terminal'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsHooksRouteImport } from './routes/settings.hooks'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsTerminalRouteImport } from './routes/settings.terminal'
import { Route as WorksIndexRouteImport } from './routes/works.index'
import { Route as WorksSlugRouteImport } from './routes/works.$slug'
import { Route as MaisonArchiveIndexRouteImport } from './routes/maison.archive.index'
import { Route as MaisonArchiveSlugRouteImport } from './routes/maison.archive.$slug'
import { Route as MaisonRoomsIndexRouteImport } from './routes/maison.rooms.index'
import { Route as MaisonRoomsSlugRouteImport } from './routes/maison.rooms.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveSlugRoute = ArchiveSlugRouteImport.update({
  id: '/archive/$slug',
  path: '/archive/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisonTerminalRoute = MaisonTerminalRouteImport.update({
  id: '/maison/terminal',
  path: '/maison/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsHooksRoute = SettingsHooksRouteImport.update({
  id: '/hooks',
  path: '/hooks',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTerminalRoute = SettingsTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => SettingsRoute,
} as any)
const WorksIndexRoute = WorksIndexRouteImport.update({
  id: '/works/',
  path: '/works/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksSlugRoute = WorksSlugRouteImport.update({
  id: '/works/$slug',
  path: '/works/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisonArchiveIndexRoute = MaisonArchiveIndexRouteImport.update({
  id: '/maison/archive/',
  path: '/maison/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisonArchiveSlugRoute = MaisonArchiveSlugRouteImport.update({
  id: '/maison/archive/$slug',
  path: '/maison/archive/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisonRoomsIndexRoute = MaisonRoomsIndexRouteImport.update({
  id: '/maison/rooms/',
  path: '/maison/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisonRoomsSlugRoute = MaisonRoomsSlugRouteImport.update({
  id: '/maison/rooms/$slug',
  path: '/maison/rooms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/terminal': typeof TerminalRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/maison/terminal': typeof MaisonTerminalRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/settings/hooks': typeof SettingsHooksRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/terminal': typeof SettingsTerminalRoute
  '/works/$slug': typeof WorksSlugRoute
  '/archive/': typeof ArchiveIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/works/': typeof WorksIndexRoute
  '/maison/archive/$slug': typeof MaisonArchiveSlugRoute
  '/maison/rooms/$slug': typeof MaisonRoomsSlugRoute
  '/maison/archive/': typeof MaisonArchiveIndexRoute
  '/maison/rooms/': typeof MaisonRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/terminal': typeof TerminalRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/maison/terminal': typeof MaisonTerminalRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/settings/hooks': typeof SettingsHooksRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/terminal': typeof SettingsTerminalRoute
  '/works/$slug': typeof WorksSlugRoute
  '/archive': typeof ArchiveIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/works': typeof WorksIndexRoute
  '/maison/archive/$slug': typeof MaisonArchiveSlugRoute
  '/maison/rooms/$slug': typeof MaisonRoomsSlugRoute
  '/maison/archive': typeof MaisonArchiveIndexRoute
  '/maison/rooms': typeof MaisonRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/terminal': typeof TerminalRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/maison/terminal': typeof MaisonTerminalRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/settings/hooks': typeof SettingsHooksRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/terminal': typeof SettingsTerminalRoute
  '/works/$slug': typeof WorksSlugRoute
  '/archive/': typeof ArchiveIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/works/': typeof WorksIndexRoute
  '/maison/archive/$slug': typeof MaisonArchiveSlugRoute
  '/maison/rooms/$slug': typeof MaisonRoomsSlugRoute
  '/maison/archive/': typeof MaisonArchiveIndexRoute
  '/maison/rooms/': typeof MaisonRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/terminal'
    | '/archive/$slug'
    | '/maison/terminal'
    | '/projects/$slug'
    | '/settings/hooks'
    | '/settings/notifications'
    | '/settings/terminal'
    | '/works/$slug'
    | '/archive/'
    | '/projects/'
    | '/settings/'
    | '/works/'
    | '/maison/archive/$slug'
    | '/maison/rooms/$slug'
    | '/maison/archive/'
    | '/maison/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/terminal'
    | '/archive/$slug'
    | '/maison/terminal'
    | '/projects/$slug'
    | '/settings/hooks'
    | '/settings/notifications'
    | '/settings/terminal'
    | '/works/$slug'
    | '/archive'
    | '/projects'
    | '/settings'
    | '/works'
    | '/maison/archive/$slug'
    | '/maison/rooms/$slug'
    | '/maison/archive'
    | '/maison/rooms'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/terminal'
    | '/archive/$slug'
    | '/maison/terminal'
    | '/projects/$slug'
    | '/settings/hooks'
    | '/settings/notifications'
    | '/settings/terminal'
    | '/works/$slug'
    | '/archive/'
    | '/projects/'
    | '/settings/'
    | '/works/'
    | '/maison/archive/$slug'
    | '/maison/rooms/$slug'
    | '/maison/archive/'
    | '/maison/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TerminalRoute: typeof TerminalRoute
  ArchiveSlugRoute: typeof ArchiveSlugRoute
  MaisonTerminalRoute: typeof MaisonTerminalRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  WorksSlugRoute: typeof WorksSlugRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  WorksIndexRoute: typeof WorksIndexRoute
  MaisonArchiveSlugRoute: typeof MaisonArchiveSlugRoute
  MaisonRoomsSlugRoute: typeof MaisonRoomsSlugRoute
  MaisonArchiveIndexRoute: typeof MaisonArchiveIndexRoute
  MaisonRoomsIndexRoute: typeof MaisonRoomsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$slug': {
      id: '/archive/$slug'
      path: '/archive/$slug'
      fullPath: '/archive/$slug'
      preLoaderRoute: typeof ArchiveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maison/terminal': {
      id: '/maison/terminal'
      path: '/maison/terminal'
      fullPath: '/maison/terminal'
      preLoaderRoute: typeof MaisonTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/hooks': {
      id: '/settings/hooks'
      path: '/hooks'
      fullPath: '/settings/hooks'
      preLoaderRoute: typeof SettingsHooksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/terminal': {
      id: '/settings/terminal'
      path: '/terminal'
      fullPath: '/settings/terminal'
      preLoaderRoute: typeof SettingsTerminalRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/works/': {
      id: '/works/'
      path: '/works'
      fullPath: '/works/'
      preLoaderRoute: typeof WorksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$slug': {
      id: '/works/$slug'
      path: '/works/$slug'
      fullPath: '/works/$slug'
      preLoaderRoute: typeof WorksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maison/archive/': {
      id: '/maison/archive/'
      path: '/maison/archive'
      fullPath: '/maison/archive/'
      preLoaderRoute: typeof MaisonArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maison/archive/$slug': {
      id: '/maison/archive/$slug'
      path: '/maison/archive/$slug'
      fullPath: '/maison/archive/$slug'
      preLoaderRoute: typeof MaisonArchiveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maison/rooms/': {
      id: '/maison/rooms/'
      path: '/maison/rooms'
      fullPath: '/maison/rooms/'
      preLoaderRoute: typeof MaisonRoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maison/rooms/$slug': {
      id: '/maison/rooms/$slug'
      path: '/maison/rooms/$slug'
      fullPath: '/maison/rooms/$slug'
      preLoaderRoute: typeof MaisonRoomsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsHooksRoute: typeof SettingsHooksRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsTerminalRoute: typeof SettingsTerminalRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsHooksRoute: SettingsHooksRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsTerminalRoute: SettingsTerminalRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TerminalRoute: TerminalRoute,
  ArchiveSlugRoute: ArchiveSlugRoute,
  MaisonTerminalRoute: MaisonTerminalRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  WorksSlugRoute: WorksSlugRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  WorksIndexRoute: WorksIndexRoute,
  MaisonArchiveSlugRoute: MaisonArchiveSlugRoute,
  MaisonRoomsSlugRoute: MaisonRoomsSlugRoute,
  MaisonArchiveIndexRoute: MaisonArchiveIndexRoute,
  MaisonRoomsIndexRoute: MaisonRoomsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
