/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as ArchiveIndexRouteImport } from './routes/archive.index'
import { Route as ArchiveSlugRouteImport } from './routes/archive.$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as WorksIndexRouteImport } from './routes/works.index'
import { Route as WorksSlugRouteImport } from './routes/works.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveSlugRoute = ArchiveSlugRouteImport.update({
  id: '/archive/$slug',
  path: '/archive/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksIndexRoute = WorksIndexRouteImport.update({
  id: '/works/',
  path: '/works/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksSlugRoute = WorksSlugRouteImport.update({
  id: '/works/$slug',
  path: '/works/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/terminal': typeof TerminalRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/works/$slug': typeof WorksSlugRoute
  '/archive/': typeof ArchiveIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/works/': typeof WorksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/terminal': typeof TerminalRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/works/$slug': typeof WorksSlugRoute
  '/archive': typeof ArchiveIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/works': typeof WorksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/terminal': typeof TerminalRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/works/$slug': typeof WorksSlugRoute
  '/archive/': typeof ArchiveIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/works/': typeof WorksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/terminal'
    | '/archive/$slug'
    | '/projects/$slug'
    | '/works/$slug'
    | '/archive/'
    | '/projects/'
    | '/works/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/terminal'
    | '/archive/$slug'
    | '/projects/$slug'
    | '/works/$slug'
    | '/archive'
    | '/projects'
    | '/works'
  id:
    | '__root__'
    | '/'
    | '/terminal'
    | '/archive/$slug'
    | '/projects/$slug'
    | '/works/$slug'
    | '/archive/'
    | '/projects/'
    | '/works/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TerminalRoute: typeof TerminalRoute
  ArchiveSlugRoute: typeof ArchiveSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  WorksSlugRoute: typeof WorksSlugRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  WorksIndexRoute: typeof WorksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$slug': {
      id: '/archive/$slug'
      path: '/archive/$slug'
      fullPath: '/archive/$slug'
      preLoaderRoute: typeof ArchiveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/': {
      id: '/works/'
      path: '/works'
      fullPath: '/works/'
      preLoaderRoute: typeof WorksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$slug': {
      id: '/works/$slug'
      path: '/works/$slug'
      fullPath: '/works/$slug'
      preLoaderRoute: typeof WorksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TerminalRoute: TerminalRoute,
  ArchiveSlugRoute: ArchiveSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  WorksSlugRoute: WorksSlugRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  WorksIndexRoute: WorksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
